# Generated by Django 5.2.5 on 2026-02-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JobPortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('junior_dev', 'Junior Developer'), ('mid_dev', 'Mid-Level Developer'), ('senior_dev', 'Senior Developer'), ('lead_dev', 'Lead Developer'), ('architect', 'Architect / Principal Developer')], default='user', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('about_me', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.TextField(blank=True, help_text='Comma separated skills (e.g. Python, Django, AWS)')),
                ('description', models.TextField()),
                ('apply_url', models.CharField(blank=True, help_text='External apply link or contact email', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hireapp.jobportaluser')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
