# Generated by Django 5.2.5 on 2026-02-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='hireapp.jobportalemployee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hireapp.jobpost'),
        ),
    ]
