# Generated by Django 5.2.5 on 2026-02-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0003_jobpost_employee_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hireapp.jobportalemployee'),
        ),
    ]
