# Generated by Django 5.2.5 on 2026-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0005_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
