# Generated by Django 5.2.5 on 2026-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0008_mocktest_question_testresult_delete_mockinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
    ]
