# Generated by Django 5.2.5 on 2026-03-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0010_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportalemployee',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
