# Generated by Django 5.2.5 on 2026-03-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0009_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
